### ISSUE TITLE
TimelineFilter gives ValueError: Header update sequence item #0 is invalid;

### ISSUE THREAD

**Issue by paultheastronomer** [spacetelescope/costools#6]
Following the example posted [here](http://costools.readthedocs.io/en/latest/timefilter.html) does not work as intended due to what I think is a problem between costools and astropy. Have a look at the following output from the python terminal:

```sh
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from costools import timefilter
The following tasks in the costools package can be run with TEAL:
         splittag                 timefilter                 x1dcorr
>>> timefilter.TimelineFilter("lcw301b2q_corrtag_b.fits")
input = /home/paw/science/betapic/COS/data/2015_1/lcw301b2q_corrtag_b.fits
GTI:  start     stop
      0.032  555.040
0.0 % of DQ column flagged with 2048

556 rows in TIMELINE
column   beginning    middle       end
time          0.03    278.03    555.03
sun_alt      28.93     12.25     -4.28
target_alt   42.10     51.64     58.93
longitude   121.77    139.87    156.68
latitude    -28.06    -25.08    -19.78
shift1     -510.47   -510.47   -510.47

column           min          max       median
shift1       -510.47      -510.47      -510.47
Ly_alpha           1          373        237.5
darkrate           0   1.7952e-05   8.0782e-06
<costools.timefilter.TimelineFilter object at 0x7f1d207d3f90>
>>> timefilter.TimelineFilter("lcw301b2q_corrtag_b.fits", "new_file.fits", "Ly_alpha < 300.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/costools/timefilter.py", line 435, in __init__
    self.setDqFlag()
  File "/usr/local/lib/python2.7/dist-packages/costools/timefilter.py", line 800, in setDqFlag
    gti = self.recomputeExptime()
  File "/usr/local/lib/python2.7/dist-packages/costools/timefilter.py", line 994, in recomputeExptime
    self.fd[self.events_hdunum].header.update(exptime_key, exptime)
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/header.py", line 1115, in update
    'a keyword, value, and comment string.'.format(idx))
ValueError: Header update sequence item #0 is invalid; the item must either be a 2-tuple containing a keyword and value, or a 3-tuple containing a keyword, value, and comment string.
>>> 
```
Anybody know what is wrong here?

**Comment by stscirij** [comment]
Yes, it looks like you've uncovered a bug that's been sitting there for a while.  The header.update() syntax is from the old pyfits days, and the old syntax was deprecated in astropy.io.fits and then removed.  I'll update the code.  Thanks for spotting this!!

**Comment by paultheastronomer** [comment]
Thank you for updating it! Could you let me know when it's been fixed? Then I can continue the analysis :)

**Comment by paultheastronomer** [comment]
My science could not wait so I implemented the changes needed and created a pull request.
