### ISSUE TITLE
x1dcorr can't find file: '$lref/x1u1459il_brf.fits'

### ISSUE THREAD

**Issue by paultheastronomer** [spacetelescope/costools#7]
When following the instructions posted in the [costools documentation](http://costools.readthedocs.io/en/latest/x1dcorr.html), I try to extract a 1D 1xdcorr spectrum from corrtag files but run into an error concerning a missing file. I am guessing I have to add this file and place it somewhere for the code to run. Any ideas?

```sh
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from costools import x1dcorr
The following tasks in the costools package can be run with TEAL:
         splittag                 timefilter                 x1dcorr
>>> x1dcorr.x1dcorr("lc9e01iaq_corrtag_b.fits", outdir="sliced/", update_input=True, find=True, cutoff=5., verbosity=2)
Input     /home/paw/science/betapic/COS/data/2014/lc9e01iaq_corrtag_b.fits
OutFlt    sliced/lc9e01iaq_flt_b.fits
OutCounts sliced/lc9e01iaq_counts_b.fits
x1d       sliced/lc9e01iaq_x1d_b.fits

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/costools/x1dcorr.py", line 185, in x1dcorr
    verbosity=verbosity)
  File "/usr/local/lib/python2.7/dist-packages/calcos/x1d.py", line 207, in extractSpec
    flt_list[i], counts_list[i])
  File "/usr/local/lib/python2.7/dist-packages/calcos/x1d.py", line 443, in makeFltCounts
    timetag.setActiveArea(events, info, reffiles["brftab"])
  File "/usr/local/lib/python2.7/dist-packages/calcos/timetag.py", line 368, in setActiveArea
    cosutil.activeArea(info["segment"], brftab)
  File "/usr/local/lib/python2.7/dist-packages/calcos/cosutil.py", line 975, in activeArea
    brf_info = getTable(brftab, {"segment": segment}, exactly_one=True)
  File "/usr/local/lib/python2.7/dist-packages/calcos/cosutil.py", line 452, in getTable
    fd = fits.open(table, mode="copyonwrite")
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/hdu/hdulist.py", line 160, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/hdu/hdulist.py", line 413, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/hdu/hdulist.py", line 998, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/usr/local/lib/python2.7/dist-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/util.py", line 395, in fileobj_open
    return open(filename, mode)
IOError: [Errno 2] No such file or directory: '$lref/x1u1459il_brf.fits'
>>> 

```

**Comment by stscirij** [comment]
Hi Paul,

You need to have the reference file available to you first, it can be downloaded from MAST when you request the data, just make sure you select the best reference files as part of the delivery.  Then you need to set the environment variable 'lref'.  This can be done in bash by doing

export lref='/where/my/reference/file/is/'

don't forget the trailing '/'.

  Let me know if this doesn't fix the problem,

  Robert Jedrzejewski

p.s. we are currently working on retiring the costools/x1dcorr script as it is incompatible with the latest versions of calcos.  We will be putting the functionality into calcos itself.  We should have a version of calcos that you can use instead of x1dcorr very soon (i.e. before the holidays).  You may find that x1dcorr doesn't work even after the fix above, let me know if that's the case.

**Comment by paultheastronomer** [comment]
Hi @stscirij 

It worked! However, as you may have guessed a new problem arose:

```sh
>>> x1dcorr.x1dcorr("lc9e01iaq_corrtag_b.fits", outdir="sliced/", update_input=True, find=True, cutoff=5., verbosity=2)

Input     /home/paw/science/betapic/COS/data/2014/lc9e01iaq_corrtag_b.fits
OutFlt    sliced/lc9e01iaq_flt_b.fits
OutCounts sliced/lc9e01iaq_counts_b.fits
x1d       sliced/lc9e01iaq_x1d_b.fits

DQICORR   PERFORM (complete, but repeat)
BPIXTAB = lref$yae1249sl_bpix.fits
GSAGTAB = lref$zbn1927gl_gsag.fits
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/costools/x1dcorr.py", line 185, in x1dcorr
    verbosity=verbosity)
  File "/usr/local/lib/python2.7/dist-packages/calcos/x1d.py", line 207, in extractSpec
    flt_list[i], counts_list[i])
  File "/usr/local/lib/python2.7/dist-packages/calcos/x1d.py", line 447, in makeFltCounts
    phdr, headers[1], minmax_shift_dict)
  File "/usr/local/lib/python2.7/dist-packages/calcos/timetag.py", line 2229, in doDqicorr
    minmax_doppler, doppler_boundary)
  File "/usr/local/lib/python2.7/dist-packages/calcos/cosutil.py", line 1209, in updateDQArray
    dq_array[lower_y_s:upper_y_s,:], info["x_offset"])
TypeError: slice indices must be integers or None or have an __index__ method
```
I am glad progress is being made on the calcos software. I am happy to keep testing for bugs. Also thank you for the prompt replies, it keeps the momentum going in my current analysis.

**Comment by paultheastronomer** [comment]
I am closing the issue as my first question was resolved.
